### ISSUE TITLE
TODO for v1.0.0-alpha1:

### ISSUE THREAD

**Issue by gulien** [gulien/orbit#1]
TODO for v1.0.0-alpha1:

- [x] Tests
- [x] orbit.yml build
- [x] Travis build
- [x] AppVeyor build
- [x] code of conduct
- [x] Issue template
- [x] Pull request template
- [x] CONTRIBUTING.md
- [x] README.md
- [x] godoc improvements
- [x] Release system
